services:
  backend:
    build: ./backend
    ports:
      - "2001:2001"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "2000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
